#!/usr/bin/env bash
python3 emulator.py -n 300 -u 3
if [ $? -ne 0 ]; then
    exit 1
fi

python3 emulator.py -n 400 -u 4
if [ $? -ne 0 ]; then
    exit 1
fi

python3 emulator.py -n 500 -u 5
if [ $? -ne 0 ]; then
    exit 1
fi
